on:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-latest-release:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      
      - name: Run all tests with latest roc release + latest basic-cli release
        run: ./ci/test_latest_release.sh
